ekmett/linear

- src/Linear/Matrix.hs
- src/Linear/Vector.hs
These are very abstract scale matrices. In projective spaces, we’re more used to using homogeneous coordinates. Then, such matrices should be higher. For instance, a 3D scaling (x, y, z) outputs a `M44` with the latest matrix cell set to `1`.
However, that can be achieved by simply passing `V4 x y z 1`.
> Scale matrices.

- src/Linear/Matrix.hs
Polymorphic identity matrix discussed in #haskell-lens ... not sure if `eye` is the best name, because it's short enough and "common" enough for possible namespace collisions with application code.
> Added 'eye', polymorphic identity matrix

- src/Linear/Matrix.hs
In the vein of "translation", which gets the last column of a matrix to
obtain the translation vector, "rotation" drops all but the first three
rows and columns to obtain a 3x3 rotation matrix.
> Add "rotation" Lens to Linear.Matrix

- src/Linear/Instances.hs
I dunno if it's too early to bother, but I saw in the travis-ci build for one of my repos that linear failed on GHC HEAD because of duplicate instances.
> add preprocessor stuff for instances that will be added in the next GHC?

- CHANGELOG.markdown
- linear.cabal
It seems `imapM_` is not available before 0.11.
> Bump vector version, for imapM_.

- linear.cabal
- src/Linear/Instances.hs
`base-orphans-0.5` now backports the orphan `Functor`/`Foldable`/`Traversable`/`Applicative`/`Monad` instances for `Complex` introduced in `base-4.9`.
> Consolidate orphan Complex instances with base-orphans

- src/Linear/Projection.hs
Multiplication by 2 has been left out in the recent floating point
precision improvements.
> Fix perspective calculation

- src/Linear/V2.hs
This is commonly used to distinguish between left and right turns in 2D.
> Add crossZ (Z-component of cross product) for V2

- src/Linear/Affine.hs
Use `newtype instance` instead of `data instance` for vectors of
`Point`.
I don't see any remotely likely downside.
> Use newtype instance for point vectors

- .gitignore
- src/Linear/Vector.hs
The default definitions for `^+^` and `^-^` don't actually use
default signatures or anything else beyond Haskell 98. Get rid
of the CPP around them, and use them unconditionally.
> Don't require unnecessary GHC support

- linear.cabal
`1.3` is shipped with GHC 8.0.2
> Relax directory constraint

- src/Linear/Trace.hs
This turns on `PolyKinds` for appropriate GHC versions in `Linear.Trace`. The particular motivation is to generalize
```haskell
instance Dim * n => Trace (V * n)
```
to the kind `Nat`, such that `trace m` compiles for types like `m :: V 5 (V 5 Double)`.
Fixes #121.
> Enable 'PolyKinds' in Linear.Trace

- src/Linear/Quaternion.hs
The previous quaternion logarithm algorithm wasn't quite correct. I don't fully understand the reasoning behind some of the edge cases handled by the quaternion code, so I can only speak for the standard case, which now matches Wikipedia's definition and seems to work correctly.
> Fix Quaternion Logarithm

- src/Linear/Plucker.hs
- src/Linear/Quaternion.hs
- src/Linear/V0.hs
- src/Linear/V1.hs
- src/Linear/V2.hs
- src/Linear/V3.hs
- src/Linear/V4.hs
The [`Lift` class](http://hackage.haskell.org/package/template-haskell-2.14.0.0/docs/Language-Haskell-TH-Syntax.html#t:Lift) allows easily using vectors in source code that have been pre-computed at compile time, i.e. in Template Haskell splices.
> Derive V0-V4 instances for the TH Lift class.

- src/Linear/Matrix.hs
I'm hoping to beef up the solver capability of `linear` a bit. Specifically, it'd be handy to have:
Unfortunately the only way I know how to implement these sorts of things efficiently is in a pseudo-imperative way. `Ixed` makes this not-too-painful, but I'll happily replace these implementations with something nicer once I work them out (or if someone beats me to it). I'm equally happy to swap out for better names for these.
> WIP: Add more solvers.

- linear.cabal
- src/Linear/V0.hs
- src/Linear/V1.hs
`random-1.2.0` removes the `randomIO` and `randomRIO` methods from `Random`. All previous releases of `random` have sensible default implementations for these methods, so they can be omitted.
> Allow building with random-1.2.*

- linear.cabal
- src/Linear/Instances.hs
`base-orphans-0.8.3` now backports the `MonadFix` and `MonadZip` instances for `Complex` (newly added to `base-4.15.0.0`) to older versions of `base`. As a result, we no longer need to define these instances as orphans in `Linear.Instances`, which allows us to turn that module into a simple shim on top of `Data.Orphans`.
> Use base-orphans-0.8.3's orphan MonadFix/MonadZip instances for Complex

- src/Linear/V.hs
`vector-0.12.2.0` (released today) exports `foldMap` which is different from `Data.Foldable.foldMap`. This breaks the compilation of `linear`. The fix is simple: qualify the use of `foldMap`.
> Specify 'foldMap' from Data.Foldable rather than Data.Vector.

- .github/workflows/haskell-ci.yml
- .hlint.yaml
- cabal.haskell-ci
- src/Linear/Affine.hs
- src/Linear/Plucker.hs
- src/Linear/Quaternion.hs
- src/Linear/V.hs
- src/Linear/V0.hs
- src/Linear/V1.hs
- src/Linear/V2.hs
- src/Linear/V3.hs
- src/Linear/V4.hs
In `random-1.2.1`, the `System.Random` module now exports a `Finite` class, which clashes with `linear`'s own `Finite` class. The fix is simple: use explicit imports from `System.Random`.
Fixes #166.
> Fix the build with random-1.2.1+ 

- linear.cabal
They are not needed on newer GHC.
>  Depend on semigroups only on GHC < 8.0
